name: 'Deploy apps'
description: 'Action for deploy'
inputs:
  app-name:
    description: 'Application id'
    required: false
    default: ''
  aws-role:
    description: 'Aws role to apply changes'
    required: true
  debug:
    description: 'Debug mode'
    default: false
  github-ssh:
    description: 'Github ssh key to pull terragrunt from github api'
    required: true
  registry:
    description: 'Registry name for app'
  sqitch:
    description: 'Only trigger sqitch deploy'
    default: false
  environment:
    description: 'Finalcad envrionment: production, staging, sandbox'
    required: true
  regions:
    description: 'Regions: eu, ap'
    default: 'eu,ap'
  tag:
    description: 'Tag to deploy'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: test
      shell: bash
      run: |
        ls -al
