name: 'Deploy apps'
description: 'Action for deploy'
inputs:
  app-name:
    description: 'Application id'
    required: true
  aws-role:
    description: 'Aws role to apply changes'
    required: true
  debug:
    description: 'Debug mode'
    default: false
  github-ssh:
    description: 'Github ssh key to pull terragrunt from github api'
    required: true
  registry:
    description: 'Registry name for app'
  sqitch:
    description: 'Only trigger sqitch deploy'
    default: false
  environment:
    description: 'Finalcad envrionment: production, staging, sandbox'
    required: true
  regions:
    description: 'Regions: eu, ap'
    default: 'eu,ap'
  tag:
    description: 'Tag to deploy'
    default: ''
  team:
    description: 'Team name for ECR'
    default: 'dotnet-backends'
runs:
  using: 'composite'
  steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        path: "deploy"
    - name: Define registry
      id: registry
      shell: bash
      run: |
        set -e
        if [ "${{ inputs.registry }}" != "" ]; then
          echo "registry=${{ inputs.registry }}" >> $GITHUB_OUTPUT
        else
          echo "registry=${{ inputs.team }}/${{ inputs.app-name }}" >> $GITHUB_OUTPUT
        fi
    - uses: FinalCAD/AppEcrAction@v1.0
      name: ECR step
      with:
        aws-role: ${{ inputs.aws-role }}
        environment: ${{ inputs.environment }}
        registry: ${{ steps.registry.outputs.registry }}
